main:
  - name: Watch
    url: https://www.youtube.com/@anchorbaptistchurchslc/streams
    weight: 10
  - name: Visit
    url: /plan-your-visit/
    weight: 20
  - name: Salvation
    url: /the-gospel/
    weight: 30
  - name: About
    url: /about/
    weight: 40
    identifier: about
  - name: Leadership
    url: /about/leadership/
    weight: 41
    parent: about
  - name: Beliefs
    url: /about/beliefs/
    weight: 42
    parent: about
  - name: Church
    url: /about/church/
    weight: 43
    parent: about
  - name: Ministries
    url: /ministries/
    weight: 50
    identifier: ministries
  - name: Sunday School
    url: /ministries/sunday-school/
    weight: 51
    parent: ministries
  - name: Children
    url: /ministries/children/
    weight: 52
    parent: ministries
  - name: Teens
    url: /ministries/teens/
    weight: 53
    parent: ministries
  - name: Adults
    url: /ministries/adults/
    weight: 54
    parent: ministries
  - name: Outreach
    url: /ministries/outreach/
    weight: 55
    parent: ministries
  - name: Missions
    url: /ministries/missions/
    weight: 56
    parent: ministries
  - name: Give
    url: https://tithe.ly/give?c=2694797
    weight: 60 