baseURL = 'https://anchorbaptistslc.org/'
languageCode = 'en-us'
title = 'Anchor Baptist Church'
theme = 'anchor-theme'

# Site Parameters
[params]
  description = "A Bible-believing church in Salt Lake City, Utah"
  address = "1880 East 5600 South, Salt Lake City, UT 84121"
  phone = "(801) 272-9405"
  email = "office@anchorbaptistslc.org"
  
  # Social Media
  [params.social]
    facebook = "https://www.facebook.com/anchorbaptistchurchslc/"
    youtube = "https://www.youtube.com/@anchorbaptistchurchslc/streams"
    instagram = "https://www.instagram.com/anchorbaptistslc/"
  
  # Service Times
  [params.services]
    sunday_school = "10:00 AM"
    sunday_morning = "11:00 AM"
    sunday_evening = "6:00 PM"
    wednesday = "7:00 PM"

# Output Formats
[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"

[build]
  writeStats = true
  noChmod = true
  noTimes = true

[build.processing]
  skip = false
[build.processing.css]
  includePaths = ["assets/css"]
  bundle = true
  minify = true

[security.exec]
  allow = ['^dart-sass-embedded$', '^git$', '^go$', '^npx$', '^postcss$', '^tailwindcss$']

[security.funcs]
  getenv = ['^HUGO_']

[security.http]
  methods = ['(?i)GET|POST']
  urls = ['.*']

[assets]
  disableHMR = false
  [assets.css]
    sourceMap = true
