baseURL = 'https://anchorbaptistslc.org/'
languageCode = 'en-us'
title = 'Anchor Baptist Church'
theme = 'anchor-theme'

# External links
[params]
  [params.external_links]
    youtube = "https://youtube.com/@anchorbaptistslc"
    tithely = "https://tithe.ly/anchorbaptistslc"

# Disable unused sections
disableKinds = ["taxonomy"]

# Output Formats
[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"

[build]
  writeStats = true
  noChmod = true
  noTimes = true

[build.processing]
  skip = false
[build.processing.css]
  includePaths = ["assets/css"]
  bundle = true
  minify = true

[build.processing.js]
  includePaths = ["assets/js"]
  bundle = true
  minify = true
  sourceMap = true

[security.exec]
  allow = ['^dart-sass-embedded$', '^git$', '^go$', '^npx$', '^postcss$', '^tailwindcss$']

[security.funcs]
  getenv = ['^HUGO_']

[security.http]
  methods = ['(?i)GET|POST']
  urls = ['.*']

[assets]
  disableHMR = false
  [assets.css]
    sourceMap = true

[imaging]
  hint = 'picture'
  quality = 85
  resampleFilter = 'Lanczos'
