name = "Anchor Theme"
license = "MIT"
licenselink = ""
description = "A modern, responsive theme for Anchor Baptist Church"
homepage = "https://anchorbaptistslc.org/"
tags = ["church", "responsive", "modern", "tailwind"]
features = ["responsive", "clean", "modern"]
min_version = "0.112.0"

[author]
  name = "Anchor Baptist Church"
  homepage = "https://anchorbaptistslc.org" 