backend:
  name: github
  repo: anchorbaptistslc/anchorbaptistslc.org
  branch: main
  use_graphql: true
  auth_url: https://github.com/login/oauth/authorize
  auth_redirect_uri: https://api.netlify.com/auth/done
  client_id: Ov23licizFSkTxXCG916

local_backend: true
local_backend_url: http://localhost:8081/api/v1

logo_url: /images/logo-anchor-60th-text-lifting-up-jesus.png
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    description: "This is the Homepage editor. Note that events are managed in the Events section."
    files:
      - name: "home"
        file: "content/_index.md"
        label: "Homepage"
        preview_path: "/admin/index.html"
        fields:
          - {label: "Page Parameters", name: "params", widget: "object", fields: [
              {label: "Show Title", name: "show_title", widget: "boolean", default: false},
              {label: "Events Section", name: "events_section", widget: "object", fields: [
                  {label: "Show Heading", name: "show_heading", widget: "boolean", default: true},
                  {label: "Heading", name: "heading", widget: "string", default: "Upcoming Events"}
                ]}
            ]}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Tagline", name: "tagline", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Call to Action", name: "cta", widget: "object", fields: [
                  {label: "Learn More", name: "learn_more", widget: "object", fields: [
                      {label: "Text", name: "text", widget: "string"},
                      {label: "URL", name: "url", widget: "string"}
                    ]},
                  {label: "Visit", name: "visit", widget: "object", fields: [
                      {label: "Text", name: "text", widget: "string"},
                      {label: "URL", name: "url", widget: "string"}
                    ]}
                ]}
            ]}
          - {label: "Worship", name: "worship", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"}
            ]}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Welcome", name: "welcome", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Image Alt Text", name: "image_alt", widget: "string"}
            ]}
          - {label: "Featured", name: "featured", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Link Text", name: "link_text", widget: "string"},
                  {label: "URL", name: "url", widget: "string"}
                ]}
            ]}

  - name: "events-overview"
    label: "Event List"
    description: "This is the Event list page that clicking an event banner from the homepage takes you to. All active events list here. Note that events are managed in the Events section."
    files:
      - name: "events-index"
        label: "Event List Page"
        file: "content/events/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "body", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
          - {label: "Type", name: "type", widget: "hidden", default: "events"}
          - {label: "Is Event", name: "isEvent", widget: "hidden", default: false}
          - {label: "Build Config", name: "_build", widget: "hidden", default: {
              list: true,
              render: true
            }}

  - name: "events-items"
    label: "Events"
    label_singular: "Event"
    description: "This is the Event editor. Add or remove events here. Only unexpired events render on the site."
    folder: "content/events"
    create: true
    filter: {field: "isEvent", value: true}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{slug}} / {{filename}}.{{extension}}"
    sortable_fields: ["title", "dates.start", "expiryDate"]
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", hint: "Shows in the banner and on the list page."}
      - {label: "Dates", name: "dates", widget: "object", fields: [
          {label: "Start", name: "start", widget: "datetime", picker_utc: true, hint: "Dates and times render with the exact time shown here."},
          {label: "End", name: "end", widget: "datetime", picker_utc: true, required: false, hint: "Only dates show when using an end date."}
        ]}
      - {label: "Expiry Date", name: "expiryDate", widget: "datetime", picker_utc: true, hint: "This is the date we stop showing this event."}
      - {label: "Banner Image", name: "image", widget: "image"}
      - {label: "Content Images", name: "content_images", widget: "list", required: false, hint: "These images show in place of the banner on the event list page.", fields: [
          {label: "Image", name: "image", widget: "image"},
          {label: "Caption", name: "caption", widget: "string", required: false}
        ]}
      - {label: "Body", name: "body", widget: "markdown", required: false, hint: "Optional and shows only on the event list page."}
      - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
      - {label: "Type", name: "type", widget: "hidden", default: "events"}
      - {label: "Is Event", name: "isEvent", widget: "hidden", default: true}
      - {label: "Build Config", name: "_build", widget: "hidden", default: {
          list: true,
          render: false
        }}

  - name: "menu-items"
    label: "Menu Links"
    label_singular: "Link"
    description: "These are links that show in the menus. They are not a full pages on the site. Use these to have menu items that link to external places such as Youtube."
    create: true
    folder: "content"
    filter: {field: "type", value: "link"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "link"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "external_url", widget: "string"}
      - label: "Menu Configuration"
        name: "menu"
        required: false
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false, hint: "Lower numbers appear first in the menu" }
              - { label: "Parent", name: "parent", widget: "select", required: false, options: ["about", "ministries"], hint: "Parent menu" }
          - label: "Footer Menu"
            name: "footer"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false }

  - name: "main-pages"
    label: "Main Pages"
    label_singular: "Page"
    description: "These are the pages at the top level of the site content structure."
    create: true
    folder: "content"
    filter: {field: "type", value: "page"}
    sortable_fields: ["menu.main.weight", "title"]
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "page"}
      - { label: "Page Layout", name: "layout", widget: "select", default: "single", options: ["single", "two-column"]}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Menu Configuration"
        name: "menu"
        required: false
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false, hint: "Lower numbers appear first in the menu" }
              - { label: "Parent", name: "parent", widget: "select", required: false, options: ["about", "ministries"], hint: "Parent menu" }
          - label: "Footer Menu"
            name: "footer"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false }

  - name: "about-pages"
    label: "About Pages"
    label_singular: "About Page"
    description: "These are the About section pages."
    folder: "content/about"
    create: true
    fields:
      - { label: "Page Layout", name: "layout", widget: "select", required: false, options: ["single", "two-column"]}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Menu Configuration"
        name: "menu"
        required: false
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Weight", name: "weight", widget: "number", hint: "Lower numbers appear first in the menu" }
              - { label: "Parent", name: "parent", widget: "select", default: "about", required: false, options: ["about"], hint: "Parent menu" }
          - label: "Footer Menu"
            name: "footer"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false }

  - name: "ministry-pages"
    label: "Ministry Pages"
    label_singular: "Ministry Page"
    description: "These are the Ministry section pages."
    folder: "content/ministries"
    create: true
    fields:
      - { label: "Page Layout", name: "layout", widget: "select", required: false, options: ["single", "two-column"]}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Meeting Time", name: "meeting_time", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Age Group", name: "age_group", widget: "string", required: false }
      - label: "Leaders"
        name: "leaders"
        required: false
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }
          - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Menu Configuration"
        name: "menu"
        required: false
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Weight", name: "weight", widget: "number", hint: "Lower numbers appear first in the menu" }
              - { label: "Parent", name: "parent", widget: "select", default: "ministries", required: false, options: ["ministries"], hint: "Parent menu" }
          - label: "Footer Menu"
            name: "footer"
            required: false
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Weight", name: "weight", widget: "number", required: false }
