backend:
  name: github
  repo: anchorbaptistslc/anchorbaptistslc.org
  branch: main
  use_graphql: true
  auth_url: https://github.com/login/oauth/authorize
  auth_redirect_uri: https://api.netlify.com/auth/done
  client_id: Ov23licizFSkTxXCG916

local_backend: true
local_backend_url: http://localhost:8081/api/v1

logo_url: /images/logo-anchor-60th-text-lifting-up-jesus.png
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    files:
      - name: "home"
        file: "content/_index.md"
        label: "Homepage"
        fields:
          - { label: "Page Parameters", name: "params", widget: "object", required: false, fields: [{ label: "Show Title", name: "show_title", widget: "boolean", default: true }] }
          - { label: "Hero", name: "hero", widget: "object", required: false, fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Tagline", name: "tagline", widget: "string" }, { label: "Image", name: "image", widget: "image" }, { label: "CTA", name: "cta", widget: "object", fields: [{ label: "Learn More", name: "learn_more", widget: "object", fields: [{ label: "Text", name: "text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }, {label: "Visit Us", name: "visit", widget: "object", fields: [{ label: "Text", name: "text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }] }] }
          - { label: "Worship", name: "worship", widget: "object", required: false, fields: [{ label: "Title", name: "title", widget: "string" }] }
          - { label: "Welcome", name: "welcome", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Image Caption", name: "image_alt", widget: "string" }] }
          - { label: "Featured", name: "featured", widget: "object", fields: [{ label: "Image", name: "image", widget: "image" }, {label: "Cards", name: "cards", widget: "list", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Description", name: "description", widget: "text" }, { label: "Link Text", name: "link_text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }] }
          - { label: "Body", name: "body", widget: "markdown" }
          

  - name: "plan-your-visit"
    label: "Visit"
    files:
      - name: "plan-your-visit"
        file: "content/plan-your-visit.md"
        label: "Plan Your Visit"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Featured Image", name: "featured_image", widget: "image" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - label: "Content Images"
            name: "content_images"
            required: false
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt_text", widget: "string" }
              - { label: "Caption", name: "caption", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "the-gospel"
    label: "Salvation"
    files:
      - name: "the-gospel"
        file: "content/the-gospel.md"
        label: "The Gospel"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Featured Image", name: "featured_image", widget: "image" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - label: "Content Images"
            name: "content_images"
            required: false
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt_text", widget: "string" }
              - { label: "Caption", name: "caption", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "about-pages"
    label: "About Pages"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "ministry-pages"
    label: "Ministry Pages"
    folder: "content/ministries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Meeting Time", name: "meeting_time", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Age Group", name: "age_group", widget: "string", required: false }
      - label: "Leaders"
        name: "leaders"
        required: false
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }
          - { label: "Bio", name: "bio", widget: "string" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }