backend:
  name: github
  repo: anchorbaptistslc/anchorbaptistslc.org
  branch: main
  use_graphql: true
  auth_url: https://github.com/login/oauth/authorize
  auth_redirect_uri: https://api.netlify.com/auth/done
  client_id: Ov23licizFSkTxXCG916

local_backend: true
local_backend_url: http://localhost:8081/api/v1

logo_url: /images/logo-anchor-60th-text-lifting-up-jesus.png
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    files:
      - name: "home"
        file: "content/_index.md"
        label: "Homepage"
        preview_path: "/admin/index.html"
        fields:
          - {label: "Page Parameters", name: "params", widget: "object", fields: [
              {label: "Show Title", name: "show_title", widget: "boolean", default: false},
              {label: "Events Section", name: "events_section", widget: "object", fields: [
                  {label: "Show Heading", name: "show_heading", widget: "boolean", default: true},
                  {label: "Heading", name: "heading", widget: "string", default: "Upcoming Events"}
                ]}
            ]}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Tagline", name: "tagline", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Call to Action", name: "cta", widget: "object", fields: [
                  {label: "Learn More", name: "learn_more", widget: "object", fields: [
                      {label: "Text", name: "text", widget: "string"},
                      {label: "URL", name: "url", widget: "string"}
                    ]},
                  {label: "Visit", name: "visit", widget: "object", fields: [
                      {label: "Text", name: "text", widget: "string"},
                      {label: "URL", name: "url", widget: "string"}
                    ]}
                ]}
            ]}
          - {label: "Events Information", name: "events_info", widget: "string", hint: "Events are managed in the Events section and will automatically appear on the homepage based on their dates. This field is for informational purposes only and will not be saved to your content."}
          - {label: "Worship", name: "worship", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"}
            ]}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Welcome", name: "welcome", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Image Alt Text", name: "image_alt", widget: "string"}
            ]}
          - {label: "Featured", name: "featured", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Link Text", name: "link_text", widget: "string"},
                  {label: "URL", name: "url", widget: "string"}
                ]}
            ]}

  - name: "events-overview"
    label: "Events"
    files:
      - name: "events-index"
        label: "Events Overview Page"
        file: "content/events/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Description", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
          - {label: "Type", name: "type", widget: "hidden", default: "events"}
          - {label: "Is Event", name: "isEvent", widget: "hidden", default: false}
          - {label: "Build Config", name: "_build", widget: "hidden", default: {
              list: true,
              render: true
            }}

  - name: "events-items"
    label: "Event Items"
    label_singular: "Event"
    folder: "content/events"
    create: true
    filter: {field: "isEvent", value: true}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Dates", name: "dates", widget: "object", fields: [
          {label: "Start", name: "start", widget: "datetime", picker_utc: true},
          {label: "End", name: "end", widget: "datetime", picker_utc: true, required: false}
        ]}
      - {label: "Expiry Date", name: "expiryDate", widget: "datetime", picker_utc: true}
      - {label: "Banner Image", name: "image", widget: "image"}
      - {label: "Content Images", name: "content_images", widget: "list", required: false, fields: [
          {label: "Image", name: "image", widget: "image"},
          {label: "Caption", name: "caption", widget: "string", required: false}
        ]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
      - {label: "Type", name: "type", widget: "hidden", default: "events"}
      - {label: "Is Event", name: "isEvent", widget: "hidden", default: true}
      - {label: "Build Config", name: "_build", widget: "hidden", default: {
          list: true,
          render: false
        }}

  - name: "plan-your-visit"
    label: "Visit"
    files:
      - name: "plan-your-visit"
        file: "content/plan-your-visit.md"
        label: "Plan Your Visit"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
          - { label: "Featured Image", name: "featured_image", widget: "image" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Content Images"
            name: "content_images"
            required: false
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt_text", widget: "string" }
              - { label: "Caption", name: "caption", widget: "string" }

  - name: "the-gospel"
    label: "Salvation"
    files:
      - name: "the-gospel"
        file: "content/the-gospel.md"
        label: "The Gospel"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
          - { label: "Featured Image", name: "featured_image", widget: "image" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Content Images"
            name: "content_images"
            required: false
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt_text", widget: "string" }
              - { label: "Caption", name: "caption", widget: "string" }

  - name: "about-pages"
    label: "About Pages"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }

  - name: "ministry-pages"
    label: "Ministry Pages"
    folder: "content/ministries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", hint: "Used for SEO metadata - keep it concise and on a single line" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Meeting Time", name: "meeting_time", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Age Group", name: "age_group", widget: "string", required: false }
      - label: "Leaders"
        name: "leaders"
        required: false
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }
          - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content Images"
        name: "content_images"
        required: false
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt_text", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
